#!/bin/bash
#
# This script is executed in the post-removal phase
#
#   On Debian,
#       $1=remove    : indicates a removal
#       $1=purge     : indicates an upgrade
#

REMOVE_USER_AND_GROUP=false
REMOVE_DIRS=false
DRUID_USER='druid'
DRUID_HOME='/opt/druid'
DRUID_LOG='/var/log/druid'
STORE_DIR="/opt/store/druid"
PERSISTENT_DIR="${STORE_DIR}/persistent/task"

case $1 in
  # Includes cases for all valid arguments, exit 1 otherwise
  # Debian
  remove)
    REMOVE_USER_AND_GROUP=true
    REMOVE_DIRS=false
  ;;
  purge)
    REMOVE_DIRS=true
  ;;
  failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|disappear)
  ;;
  *)
      echo "post remove script called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

if [ ${REMOVE_USER_AND_GROUP} = "true" ]; then
  echo "Deleting ${DRUID_USER} user..."

  if getent passwd ${DRUID_USER} >/dev/null; then
    userdel -r ${DRUID_USER}
  fi
fi

if [ ${REMOVE_DIRS} = "true" ]; then
  if [ -d ${DRUID_HOME} ]; then
    echo "Removing Druid directories..."
    rm -rf ${DRUID_HOME} && echo " ...OK"
  fi
  if [ -d ${DRUID_LOG} ]; then
    echo "Removing Druid logs..."
    rm -rf ${DRUID_LOG} && echo " ...OK"
  fi

  if [ -d ${STORE_DIR} ]
  then
    echo "Deleting Druid store directory..."
    rm -rf ${STORE_DIR} && echo "... OK"
  fi

  if command -v systemctl >/dev/null; then
    systemctl daemon-reload
  fi
fi

exit 0
